openapi: 3.0.2
info:
  version: 0.1.0
  title: {{ cookiecutter.project_name }}-api
  license:
    name: MIT
  contact:
    email: support@flowlab.no
servers:
  - url: https://flowlab.no
tags:
  - name: Event
paths:
  /event:
    post:
      summary: Post an event
      operationId: postEvent
      requestBody:
        description: Event object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      tags:
        - events
      responses:
        '202':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-amazon-apigateway-request-validator:
        all:
          validateRequestBody: true
          validateRequestParameters: true
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
        responses:
          default:
            statusCode: "202"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
components:
  schemas:
    Event:
      required:
        - name
      properties:
        name:
          type: string
    Error:
      required:
        - message
      properties:
        message:
          type: string